name: Spring Boot & Gradle CI/CD

on:
  push:
    branches: [ "main" ]


permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Grant execute permission for gradlew
        run: chmod +x ./back/gradlew

      - name: Build with Gradle
        run: |
          cd back
          ./gradlew clean build -x test

      # 디렉토리 생성
      - name: Make Directory
        run: mkdir -p deploy

      # Jar 파일 복사
      - name: Copy Jar
        run: cp ./back/build/libs/*.jar ./deploy

      - name: Copy script
        run: |
          mkdir -p deploy/scripts
          cp ./scripts/* ./deploy/scripts


      - name: Make zip file
        run: zip -r ./damda.zip ./deploy appspec.yml
        shell: bash

      # 압축 풀기
      - name: Unzip deployment package
        run: unzip -o ./damda.zip -d ./deploy
        shell: bash

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-northeast-2

      # Upload to S3
      - name: Upload to S3
        run: aws s3 cp --region ap-northeast-2 ./damda.zip s3://damda-actions

      # Deploy
      - name: Deploy
        run: |
          aws deploy create-deployment \
          --application-name damda-action-application \
          --deployment-config-name CodeDeployDefault.AllAtOnce \
          --deployment-group-name damda-application-group-deploy \
          --file-exists-behavior OVERWRITE \
          --s3-location bucket=damda-actions,bundleType=zip,key=damda.zip \
          --region ap-northeast-2
